name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - orders/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build Docker image
        run: cd orders && docker build -t causeleea/orders .

      - name: Push Docker image
        run: docker push causeleea/orders
      
      - name: installing doctl digital ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN}}
          
      - name: cluster configuration 
        run: doctl kubernetes cluster kubeconfig save ticketingdev
        
      - name: restarting deployment
        run: kubectl rollout restart deployment orders-depl









        
