name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - auth/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: build and deploy
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t causeleea/auth .
      - run: docker push causeleea/auth
